### ISSUE TITLE
help

### ISSUE THREAD

**Issue by logandark** [SplitPixl/snekbot#3]

**Comment by martmists** [comment]
Wew lad, no wonder everyone bans you from their github

**Comment by Vap0r1ze** [comment]
This is why you got banned from my server, being an idiot

**Comment by bubbie** [comment]
stop being a moron you stupid fuck

**Comment by SplitPixl** [comment]
This is not related to snekbot in any way.

**Comment by aurieh** [comment]
good shit :ok_hand: 




heh

**Comment by TripingPC** [comment]
dank.  



just dank.

**Comment by SplitPixl** [comment]
People on the internet are stupid, please fix.

**Comment by eslachance** [comment]
This is why you're pre-banned from the new Discord.js official server, and the discord.js repo, and so many places it's not even funny anymore.

**Comment by bubbie** [comment]
@SplitPixl mong

**Comment by SplitPixl** [comment]
why

**Comment by AlexFlipnote** [comment]
lolololol #rekt 
👌👌👌🍪
